version: '3.8'

services:
  my-rust-compiler:
    image: rust:latest
    container_name: my-rust-compiler
    volumes:
      - ./src:/app
    working_dir: /app
    command: sleep infinity
    depends_on:
      - db
    networks:
      - devnet

  db:
    image: mongo:latest
    container_name: rust_db
    ports:
      - "27017:27017"
    volumes: 
      - ./mongo/data:/data/db
    networks:
      - devnet

networks:
  devnet:
